name: ahmed
favicon: null
layout_spectrum: 0.09344091173261404
typography_spectrum: 0.10712043405510485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9512771661393344
  lightness: 0.577081038383767
  saturation: 0.1862811455503106
  rhythmicContrast: 0.833391709253192
purpose: []
